# Generated by Django 5.1.6 on 2025-05-31 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0012_alter_income_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ["-date"],
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="income",
            name="description",
            field=models.CharField(
                blank=True,
                choices=[
                    ("salary", "Salary"),
                    ("bonus", "Bonus"),
                    ("investment", "Investment"),
                    ("rent", "Rent"),
                    ("sale", "Sale"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
