# Generated by Django 5.1.6 on 2025-06-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0014_alter_expense_category_alter_income_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Income",
        ),
    ]
